var Albums = {
  albums: [
    { title: "Sgt. Peppers Lonely Hearts Club Band", artist: "The Beatles" },
    { title: "Pet Sounds", artist: "The Beach Boys" },
    { title: "Revolver", artist: "The Beatles" },
    { title: "Highway 61 Revisited", artist: "Bob Dylan" },
    { title: "Rubber Soul", artist: "The Beatles" },
    { title: "Whats Going On", artist: "Marvin Gaye" },
    { title: "Exile on Main St.", artist: "The Rolling Stones" },
    { title: "London Calling", artist: "The Clash" },
    { title: "Blonde On Blonde", artist: "Bob Dylan" },
    { title: "The White Album", artist: "The Beatles" },
    { title: "The Sun Sessions", artist: "Elvis Presley" },
    { title: "Kind Of Blue", artist: "Miles Davis" },
    { title: "The Velvet Underground & Nico", artist: "The Velvet Underground" },
    { title: "Abbey Road", artist: "The Beatles" },
    { title: "Are You Experienced", artist: "The Jimi Hendrix Experience" },
    { title: "Blood On The Tracks", artist: "Bob Dylan" },
    { title: "Nevermind", artist: "Nirvana" },
    { title: "Born To Run", artist: "Bruce Springsteen" },
    { title: "Astral Weeks", artist: "Van Morrison" },
    { title: "Thriller", artist: "Michael Jackson" },
    { title: "The Great Twenty-Eight", artist: "Chuck Berry" },
    { title: "John Lennon/Plastic Ono Band", artist: "John Lennon" },
    { title: "Innervisions", artist: "Stevie Wonder" },
    { title: "Live At The Apollo", artist: "James Brown" },
    { title: "Rumours", artist: "Fleetwood Mac" },
    { title: "The Joshua Tree", artist: "U2" },
    { title: "King Of The Delta Blues Singers Vol.1", artist: "Robert Johnson" },
    { title: "Whos Next", artist: "The Who" },
    { title: "Led Zeppelin", artist: "Led Zeppelin" },
    { title: "Blue", artist: "Joni Mitchell" },
    { title: "Bringing It All Back Home", artist: "Bob Dylan" },
    { title: "Let It Bleed", artist: "The Rolling Stones" },
    { title: "Ramones", artist: "Ramones" },
    { title: "Music From Big Pink", artist: "The Band" },
    { title: "The Rise And Fall Of Ziggy Stardust And The Spiders From Mars", artist: "David Bowie" },
    { title: "Tapestry", artist: "Carole King" },
    { title: "Hotel California", artist: "Eagles" },
    { title: "The Anthology (1947-1972)", artist: "Muddy Waters" },
    { title: "Please Please Me", artist: "The Beatles" },
    { title: "Forever Changes", artist: "Love" },
    { title: "Never Mind The Bollocks Heres The Sex Pistols", artist: "Sex Pistols" },
    { title: "The Doors", artist: "The Doors" },
    { title: "The Dark Side Of The Moon", artist: "Pink Floyd" },
    { title: "Horses", artist: "Patti Smith" },
    { title: "The Band", artist: "The Band" },
    { title: "Legend", artist: "Bob Marley & The Wailers" },
    { title: "A Love Supreme", artist: "John Coltrane" },
    { title: "It Takes A Nation Of Millions To Hold Us Back", artist: "Public Enemy" },
    { title: "At Fillmore East", artist: "The Allman Brothers Band" },
    { title: "Heres Little Richard", artist: "Little Richard" },
    { title: "Bridge Over Troubled Water", artist: "Simon And Garfunkel" },
    { title: "Greatest Hits", artist: "Al Green" },
    { title: "The Birth Of Soul: The Complete Atlantic Rhythm And Blues Recordings", artist: "Ray Charles" },
    { title: "Electric Ladyland", artist: "The Jimi Hendrix Experience" },
    { title: "Elvis Presley", artist: "Elvis Presley" },
    { title: "Songs In The Key Of Life", artist: "Stevie Wonder" },
    { title: "Beggars Banquet", artist: "The Rolling Stones" },
    { title: "Trout Mask Replica", artist: "Captain Beefheart and his Magic Band" },
    { title: "Meet The Beatles", artist: "The Beatles" },
    { title: "Greatest Hits", artist: "Sly & The Family Stone" },
    { title: "Appetite For Destruction", artist: "Guns N Roses" },
    { title: "Achtung Baby", artist: "U2" },
    { title: "Sticky Fingers", artist: "The Rolling Stones" },
    { title: "Back To Mono", artist: "Phil Spector" },
    { title: "Moondance", artist: "Van Morrison" },
    { title: "Led Zeppelin IV", artist: "Led Zeppelin" },
    { title: "The Stranger", artist: "Billy Joel" },
    { title: "Off The Wall", artist: "Michael Jackson" },
    { title: "Super Fly", artist: "Curtis Mayfield" },
    { title: "Physical Graffiti", artist: "Led Zeppelin" },
    { title: "After The Gold Rush", artist: "Neil Young" },
    { title: "Purple Rain", artist: "Prince" },
    { title: "Back In Black", artist: "AC/DC" },
    { title: "Otis Blue", artist: "Otis Redding" },
    { title: "Led Zeppelin II", artist: "Led Zeppelin" },
    { title: "Imagine", artist: "John Lennon" },
    { title: "The Clash", artist: "The Clash" },
    { title: "Harvest", artist: "Neil Young" },
    { title: "Star Time", artist: "James Brown" },
    { title: "Odessey And Oracle", artist: "The Zombies" },
    { title: "Graceland", artist: "Paul Simon" },
    { title: "Axis: Bold As Love", artist: "The Jimi Hendrix Experience" },
    { title: "I Never Loved A Man The Way I Love You", artist: "Aretha Franklin" },
    { title: "Lady Soul", artist: "Aretha Franklin" },
    { title: "Born In The U.S.A.", artist: "Bruce Springsteen" },
    { title: "Let It Be", artist: "The Beatles" },
    { title: "The Wall", artist: "Pink Floyd" },
    { title: "At Folsom Prison", artist: "Johnny Cash" },
    { title: "Dusty In Memphis", artist: "Dusty Springfield" },
    { title: "Talking Book", artist: "Stevie Wonder" },
    { title: "Goodbye Yellow Brick Road", artist: "Elton John" },
    { title: "20 Golden Greats", artist: "Buddy Holly" },
    { title: "Sign O The Times", artist: "Prince" },
    { title: "Bitches Brew", artist: "Miles Davis" },
    { title: "Green River", artist: "Creedence Clearwater Revival" },
    { title: "Tommy", artist: "The Who" },
    { title: "The Freewheelin Bob Dylan", artist: "Bob Dylan" },
    { title: "This Years Model", artist: "Elvis Costello" },
    { title: "There's A Riot Goin' On", artist: "Sly & The Family Stone" },
    { title: "In The Wee Small Hours", artist: "Frank Sinatra" },
    { title: "Fresh Cream", artist: "Cream" },
    { title: "Giant Steps", artist: "John Coltrane" },
    { title: "Sweet Baby James", artist: "James Taylor" },
    { title: "Modern Sounds In Country And Western Music", artist: "Ray Charles" },
    { title: "Rocket To Russia", artist: "Ramones" },
    { title: "Portrait Of A Legend: 1951-1964", artist: "Sam Cooke" },
    { title: "Hunky Dory", artist: "David Bowie" },
    { title: "Aftermath", artist: "The Rolling Stones" },
    { title: "Loaded", artist: "The Velvet Underground" },
    { title: "The Bends", artist: "Radiohead" },
    { title: "Court And Spark", artist: "Joni Mitchell" },
    { title: "Disraeli Gears", artist: "Cream" },
    { title: "The Who Sell Out", artist: "The Who" },
    { title: "Out Of Our Heads", artist: "The Rolling Stones" },
    { title: "Layla And Other Assorted Love Songs", artist: "Derek And The Dominos" },
    { title: "At Last!", artist: "Etta James" },
    { title: "Sweetheart Of The Rodeo", artist: "The Byrds" },
    { title: "Stand!", artist: "Sly & The Family Stone" },
    { title: "The Harder They Come", artist: "Jimmy Cliff" },
    { title: "Raising Hell", artist: "Run-D.M.C." },
    { title: "Moby Grape", artist: "Moby Grape" },
    { title: "Pearl", artist: "Janis Joplin" },
    { title: "Catch A Fire", artist: "Bob Marley & The Wailers & The Wailers" },
    { title: "Younger Than Yesterday", artist: "The Byrds" },
    { title: "Raw Power", artist: "The Stooges" },
    { title: "Remain In Light", artist: "Talking Heads" },
    { title: "If You Can Believe Your Eyes And Ears", artist: "The Mamas & The Papas" },
    { title: "Marquee Moon", artist: "Television" },
    { title: "40 Greatest Hits", artist: "Hank Williams" },
    { title: "Paranoid", artist: "Black Sabbath" },
    { title: "Saturday Night Fever (Original Soundtrack)", artist: "Various Artists" },
    { title: "The Wild The Innocent And The E Street Shuffle", artist: "Bruce Springsteen" },
    { title: "Ready To Die", artist: "The Notorious B.I.G." },
    { title: "Slanted And Enchanted", artist: "Pavement" },
    { title: "Greatest Hits", artist: "Elton John" },
    { title: "Tim", artist: "The Replacements" },
    { title: "The Chronic", artist: "Dr. Dre" },
    { title: "Rejuvenation", artist: "The Meters" },
    { title: "All That You Cant Leave Behind", artist: "U2" },
    { title: "Parallel Lines", artist: "Blondie" },
    { title: "Live At The Regal", artist: "B.B. King" },
    { title: "A Christmas Gift For You", artist: "Phil Spector" },
    { title: "Gris-Gris", artist: "Dr. John" },
    { title: "Straight Outta Compton", artist: "N.W.A" },
    { title: "Aja", artist: "Steely Dan" },
    { title: "Surrealistic Pillow", artist: "Jefferson Airplane" },
    { title: "Dreams To Remember: The Otis Redding Anthology", artist: "Otis Redding" },
    { title: "Déjà Vu", artist: "Crosby Stills Nash & Young" },
    { title: "Houses Of The Holy", artist: "Led Zeppelin" },
    { title: "Santana", artist: "Santana" },
    { title: "Darkness On The Edge Of Town", artist: "Bruce Springsteen" },
    { title: "The B-52s", artist: "The B-52s" },
    { title: "Moanin In The Moonlight", artist: "Howlin Wolf" },
    { title: "The Low End Theory", artist: "A Tribe Called Quest" },
    { title: "Pretenders", artist: "Pretenders" },
    { title: "Pauls Boutique", artist: "Beastie Boys" },
    { title: "Closer", artist: "Joy Division" },
    { title: "Captain Fantastic And The Brown Dirt Cowboy", artist: "Elton John" },
    { title: "Alive", artist: "Kiss" },
    { title: "Electric Warrior", artist: "T. Rex" },
    { title: "The Dock Of The Bay", artist: "Otis Redding" },
    { title: "OK Computer", artist: "Radiohead" },
    { title: "1999", artist: "Prince" },
    { title: "Heart Like A Wheel", artist: "Linda Ronstadt" },
    { title: "Lets Get It On", artist: "Marvin Gaye" },
    { title: "Imperial Bedroom", artist: "Elvis Costello" },
    { title: "Master Of Puppets", artist: "Metallica" },
    { title: "My Aim Is True", artist: "Elvis Costello" },
    { title: "Exodus", artist: "Bob Marley & The Wailers" },
    { title: "Live At Leeds", artist: "The Who" },
    { title: "The Notorious Byrd Brothers", artist: "The Byrds" },
    { title: "Every Picture Tells A Story", artist: "Rod Stewart" },
    { title: "Something/Anything?", artist: "Todd Rundgren" },
    { title: "Desire", artist: "Bob Dylan" },
    { title: "Close To You", artist: "Carpenters" },
    { title: "Rocks", artist: "Aerosmith" },
    { title: "One Nation Under A Groove", artist: "Parliament/Funkadelic" },
    { title: "Greatest Hits", artist: "The Byrds" },
    { title: "The Anthology 1961 - 1977", artist: "Curtis Mayfield And The Impressions" },
    { title: "The Definitive Collection", artist: "ABBA" },
    { title: "The Rolling Stones Now!", artist: "The Rolling Stones" },
    { title: "Natty Dread", artist: "Bob Marley & The Wailers & The Wailers" },
    { title: "Fleetwood Mac", artist: "Fleetwood Mac" },
    { title: "Red Headed Stranger", artist: "Willie Nelson" },
    { title: "The Stooges", artist: "The Stooges" },
    { title: "Fresh", artist: "Sly & The Family Stone" },
    { title: "So", artist: "Peter Gabriel" },
    { title: "Buffalo Springfield Again", artist: "Buffalo Springfield" },
    { title: "Happy Trails", artist: "Quicksilver Messenger Service" },
    { title: "From Elvis In Memphis", artist: "Elvis Presley" },
    { title: "Fun House", artist: "The Stooges" },
    { title: "The Gilded Palace Of Sin", artist: "The Flying Burrito Brothers" },
    { title: "Dookie", artist: "Green Day" },
    { title: "Transformer", artist: "Lou Reed" },
    { title: "Blues Breakers With Eric Clapton", artist: "John Mayall" },
    { title: "Nuggets: Original Artyfacts From The First Psychedelic Era 1965-1968", artist: "Various Artists" },
    { title: "Murmur", artist: "R.E.M." },
    { title: "The Best Of", artist: "Little Walter" },
    { title: "Highway To Hell", artist: "AC/DC" },
    { title: "The Downward Spiral", artist: "Nine Inch Nails" },
    { title: "Parsley Sage Rosemary And Thyme", artist: "Simon And Garfunkel" },
    { title: "Bad", artist: "Michael Jackson" },
    { title: "Wheels Of Fire", artist: "Cream" },
    { title: "Dirty Mind", artist: "Prince" },
    { title: "Abraxas", artist: "Santana" },
    { title: "Tea For The Tillerman", artist: "Cat Stevens" },
    { title: "Ten", artist: "Pearl Jam" },
    { title: "Everybody Knows This Is Nowhere", artist: "Neil Young & Crazy Horse" },
    { title: "Wish You Were Here", artist: "Pink Floyd" },
    { title: "Crooked Rain Crooked Rain", artist: "Pavement" },
    { title: "Tattoo You", artist: "The Rolling Stones" },
    { title: "Proud Mary: The Best Of Ike And Tina Turner", artist: "Ike And Tina Turner" },
    { title: "New York Dolls", artist: "New York Dolls" },
    { title: "Go Bo Diddley", artist: "Bo Diddley" },
    { title: "Two Steps From The Blues", artist: "Bobby Bland" },
    { title: "The Queen Is Dead", artist: "The Smiths" },
    { title: "Licensed To Ill", artist: "Beastie Boys" },
    { title: "Look-Ka Py Py", artist: "The Meters" },
    { title: "Loveless", artist: "My Bloody Valentine" },
    { title: "New Orleans Piano", artist: "Professor Longhair" },
    { title: "War", artist: "U2" },
    { title: "The Neil Diamond Collection", artist: "Neil Diamond" },
    { title: "Howlin Wolf", artist: "Howlin Wolf" },
    { title: "Nebraska", artist: "Bruce Springsteen" },
    { title: "The Complete Hank Williams", artist: "Hank Williams" },
    { title: "Doolittle", artist: "Pixies" },
    { title: "Paid In Full", artist: "Eric B. And Rakim" },
    { title: "Toys In The Attic", artist: "Aerosmith" },
    { title: "Nick Of Time", artist: "Bonnie Raitt" },
    { title: "A Night At The Opera", artist: "Queen" },
    { title: "The Kink Kronikles", artist: "The Kinks" },
    { title: "Mr. Tambourine Man", artist: "The Byrds" },
    { title: "Bookends", artist: "Simon And Garfunkel" },
    { title: "The Ultimate Collection", artist: "Patsy Cline" },
    { title: "Mr. Excitement!", artist: "Jackie Wilson" },
    { title: "The Who Sings My Generation", artist: "The Who" },
    { title: "Like A Prayer", artist: "Madonna" },
    { title: "Cant Buy A Thrill", artist: "Steely Dan" },
    { title: "Let It Be", artist: "The Replacements" },
    { title: "Run-DMC", artist: "Run-DMC" },
    { title: "Black Sabbath", artist: "Black Sabbath" },
    { title: "The Jerry Lee Lewis Anthology: All Killer No Filler!", artist: "Jerry Lee Lewis" },
    { title: "Freak Out!", artist: "The Mothers Of Invention" },
    { title: "Live Dead", artist: "Grateful Dead" },
    { title: "Bryter Layter", artist: "Nick Drake" },
    { title: "The Shape Of Jazz To Come", artist: "Ornette Coleman" },
    { title: "Automatic For The People", artist: "R.E.M." },
    { title: "Reasonable Doubt", artist: "Jay-Z" },
    { title: "Low", artist: "David Bowie" },
    { title: "The River", artist: "Bruce Springsteen" },
    { title: "Complete & Unbelievable: The Otis Redding Dictionary Of Soul", artist: "Otis Redding" },
    { title: "Metallica", artist: "Metallica" },
    { title: "Trans-Europe Express", artist: "Kraftwerk" },
    { title: "Whitney Houston", artist: "Whitney Houston" },
    { title: "The Kinks Are The Village Green Preservation Society", artist: "The Kinks" },
    { title: "The Velvet Rope", artist: "Janet Jackson" },
    { title: "Stardust", artist: "Willie Nelson" },
    { title: "American Beauty", artist: "Grateful Dead" },
    { title: "Crosby Stills & Nash", artist: "Crosby Stills & Nash" },
    { title: "Buena Vista Social Club", artist: "Buena Vista Social Club" },
    { title: "Tracy Chapman", artist: "Tracy Chapman" },
    { title: "Workingmans Dead", artist: "Grateful Dead" },
    { title: "The Genius Of Ray Charles", artist: "Ray Charles" },
    { title: "Child Is Father To The Man", artist: "Blood, Sweat & Tears" },
    { title: "Cosmos Factory", artist: "Creedence Clearwater Revival" },
    { title: "Quadrophenia", artist: "The Who" },
    { title: "There Goes Rhymin Simon", artist: "Paul Simon" },
    { title: "Psycho Candy", artist: "The Jesus And Mary Chain" },
    { title: "Some Girls", artist: "The Rolling Stones" },
    { title: "The Beach Boys Today!", artist: "The Beach Boys" },
    { title: "Going To A Go-Go", artist: "Smokey Robinson And The Miracles" },
    { title: "Nightbirds", artist: "Labelle" },
    { title: "The Slim Shady LP", artist: "Eminem" },
    { title: "Mothership Connection", artist: "Parliament" },
    { title: "Rhythm Nation 1814", artist: "Janet Jackson" },
    { title: "Anthology Of American Folk Music", artist: "Various Artists" },
    { title: "Aladdin Sane", artist: "David Bowie" },
    { title: "The Immaculate Collection", artist: "Madonna" },
    { title: "My Life", artist: "Mary J. Blige" },
    { title: "Folk Singer", artist: "Muddy Waters" },
    { title: "Cant Get Enough", artist: "Barry White" },
    { title: "The Cars", artist: "The Cars" },
    { title: "Five Leaves Left", artist: "Nick Drake" },
    { title: "Music Of My Mind", artist: "Stevie Wonder" },
    { title: "Im Still In Love With You", artist: "Al Green" },
    { title: "Los Angeles", artist: "X" },
    { title: "Anthem Of The Sun", artist: "Grateful Dead" },
    { title: "Something Else By The Kinks", artist: "The Kinks" },
    { title: "Call Me", artist: "Al Green" },
    { title: "Talking Heads: 77", artist: "Talking Heads" },
    { title: "The Basement Tapes", artist: "Bob Dylan And The Band" },
    { title: "White Light/White Heat", artist: "The Velvet Underground" },
    { title: "Greatest Hits", artist: "Simon And Garfunkel" },
    { title: "Kick Out The Jams", artist: "MC5" },
    { title: "Meat Is Murder", artist: "The Smiths" },
    { title: "Were Only In It For The Money", artist: "The Mothers Of Invention" },
    { title: "The Blue Album", artist: "Weezer" },
    { title: "Master Of Reality", artist: "Black Sabbath" },
    { title: "Coat Of Many Colors", artist: "Dolly Parton" },
    { title: "Fear Of A Black Planet", artist: "Public Enemy" },
    { title: "John Wesley Harding", artist: "Bob Dylan" },
    { title: "The Marshall Mathers LP", artist: "Eminem" },
    { title: "Grace", artist: "Jeff Buckley" },
    { title: "Car Wheels On A Gravel Road", artist: "Lucinda Williams" },
    { title: "Odelay", artist: "Beck" },
    { title: "Songs For Swingin Lovers", artist: "Frank Sinatra" },
    { title: "Avalon", artist: "Roxy Music" },
    { title: "The Sun Records Collection", artist: "Various Artists" },
    { title: "Nothings Shocking", artist: "Janes Addiction" },
    { title: "Blood Sugar Sex Magik", artist: "Red Hot Chili Peppers" },
    { title: "Unplugged In New York", artist: "Nirvana" },
    { title: "The Miseducation Of Lauryn Hill", artist: "Lauryn Hill" },
    { title: "Damn The Torpedoes", artist: "Tom Petty And The Heartbreakers" },
    { title: "The Velvet Underground", artist: "The Velvet Underground" },
    { title: "Surfer Rosa", artist: "Pixies" },
    { title: "Rock Steady", artist: "No Doubt" },
    { title: "The Eminem Show", artist: "Eminem" },
    { title: "Back Stabbers", artist: "The OJays" },
    { title: "Burnin", artist: "Bob Marley & The Wailers & The Wailers" },
    { title: "Pink Moon", artist: "Nick Drake" },
    { title: "Sail Away", artist: "Randy Newman" },
    { title: "Ghost In The Machine", artist: "The Police" },
    { title: "Station To Station", artist: "David Bowie" },
    { title: "The Very Best Of Linda Ronstadt", artist: "Linda Ronstadt" },
    { title: "Slowhand", artist: "Eric Clapton" },
    { title: "Disintegration", artist: "The Cure" },
    { title: "Jagged Little Pill", artist: "Alanis Morissette" },
    { title: "Exile In Guyville", artist: "Liz Phair" },
    { title: "Daydream Nation", artist: "Sonic Youth" },
    { title: "In The Jungle Groove", artist: "James Brown" },
    { title: "Tonights The Night", artist: "Neil Young" },
    { title: "Help!", artist: "The Beatles" },
    { title: "Shoot Out The Lights", artist: "Richard & Linda Thompson" },
    { title: "Wild Gift", artist: "X" },
    { title: "Squeezing Out Sparks", artist: "Graham Parker" },
    { title: "Superunknown", artist: "Soundgarden" },
    { title: "Aqualung", artist: "Jethro Tull" },
    { title: "Cheap Thrills", artist: "Big Brother And The Holding Company" },
    { title: "The Heart Of Saturday Night", artist: "Tom Waits" },
    { title: "Damaged", artist: "Black Flag" },
    { title: "Play", artist: "Moby" },
    { title: "Violator", artist: "Depeche Mode" },
    { title: "Bat Out Of Hell", artist: "Meat Loaf" },
    { title: "Berlin", artist: "Lou Reed" },
    { title: "Stop Making Sense", artist: "Talking Heads" },
    { title: "3 Feet High And Rising", artist: "De La Soul" },
    { title: "The Piper At The Gates Of Dawn", artist: "Pink Floyd" },
    { title: "At Newport 1960", artist: "Muddy Waters" },
    { title: "Roger The Engineer", artist: "The Yardbirds" },
    { title: "Rust Never Sleeps", artist: "Neil Young & Crazy Horse" },
    { title: "Brothers In Arms", artist: "Dire Straits" },
    { title: "52nd Street", artist: "Billy Joel" },
    { title: "Having A Rave Up With The Yardbirds", artist: "The Yardbirds" },
    { title: "12 Songs", artist: "Randy Newman" },
    { title: "Between The Buttons", artist: "The Rolling Stones" },
    { title: "Sketches Of Spain", artist: "Miles Davis" },
    { title: "Honky Chateau", artist: "Elton John" },
    { title: "Singles Going Steady", artist: "Buzzcocks" },
    { title: "Stankonia", artist: "OutKast" },
    { title: "Siamese Dream", artist: "Smashing Pumpkins" },
    { title: "Substance", artist: "New Order" },
    { title: "L.A. Woman", artist: "The Doors" },
    { title: "Ray Of Light", artist: "Madonna" },
    { title: "American Recordings", artist: "Johnny Cash" },
    { title: "Louder Than Bombs", artist: "The Smiths" },
    { title: "Mott", artist: "Mott The Hoople" },
    { title: "Is This It", artist: "The Strokes" },
    { title: "Rage Against The Machine", artist: "Rage Against The Machine" },
    { title: "Reggatta De Blanc", artist: "The Police" },
    { title: "Volunteers", artist: "Jefferson Airplane" },
    { title: "Siren", artist: "Roxy Music" },
    { title: "Late For The Sky", artist: "Jackson Browne" },
    { title: "Post", artist: "Björk" },
    { title: "Eagles", artist: "Eagles" },
    { title: "The Ultimate Collection (1948 - 1990)", artist: "John Lee Hooker" },
    { title: "(Whats The Story) Morning Glory?", artist: "Oasis" },
    { title: "CrazySexyCool", artist: "TLC" },
    { title: "Funky Kingston", artist: "Toots And The Maytals" },
    { title: "Greetings From Asbury Park", artist: "Bruce Springsteen" },
    { title: "Sunflower", artist: "The Beach Boys" },
    { title: "Modern Lovers", artist: "Modern Lovers" },
    { title: "More Songs About Buildings And Food", artist: "Talking Heads" },
    { title: "A Quick One (Happy Jack)", artist: "The Who" },
    { title: "Pyromania", artist: "Def Leppard" },
    { title: "Pretzel Logic", artist: "Steely Dan" },
    { title: "Enter The Wu-Tang: 36 Chambers", artist: "Wu-Tang Clan" },
    { title: "Country Life", artist: "Roxy Music" },
    { title: "A Hard Days Night", artist: "The Beatles" },
    { title: "The End Of The Innocence", artist: "Don Henley" },
    { title: "Elephant", artist: "The White Stripes" },
    { title: "The Pretender", artist: "Jackson Browne" },
    { title: "Willy And The Poor Boys", artist: "Creedence Clearwater Revival" },
    { title: "Good Old Boys", artist: "Randy Newman" },
    { title: "For Your Pleasure", artist: "Roxy Music" },
    { title: "Blue Lines", artist: "Massive Attack" },
    { title: "Eliminator", artist: "ZZ Top" },
    { title: "Rain Dogs", artist: "Tom Waits" },
    { title: "Anthology", artist: "The Temptations" },
    { title: "Californication", artist: "Red Hot Chili Peppers" },
    { title: "Illmatic", artist: "Nas" },
    { title: "(Pronounced Leh-Nerd Skin-Nerd)", artist: "Lynyrd Skynyrd" },
    { title: "Dr. Johns Gumbo", artist: "Dr. John" },
    { title: "Radio City", artist: "Big Star" },
    { title: "Sandinista!", artist: "The Clash" },
    { title: "Rid Of Me", artist: "PJ Harvey" },
    { title: "I Do Not Want What I Havent Got", artist: "Sinead OConnor" },
    { title: "Strange Days", artist: "The Doors" },
    { title: "Time Out Of Mind", artist: "Bob Dylan" },
    { title: "461 Ocean Boulevard", artist: "Eric Clapton" },
    { title: "Pink Flag", artist: "Wire" },
    { title: "Double Nickels On The Dime", artist: "Minutemen" },
    { title: "Mezzanine", artist: "Massive Attack" },
    { title: "Beauty And The Beat", artist: "Go-Gos" },
    { title: "Greatest Hits", artist: "James Brown" },
    { title: "Van Halen", artist: "Van Halen" },
    { title: "Mule Variations", artist: "Tom Waits" },
    { title: "Boy", artist: "U2" },
    { title: "Band On The Run", artist: "Wings" },
    { title: "Dummy", artist: "Portishead" },
    { title: "With The Beatles", artist: "The Beatles" },
    { title: "The Chirping Crickets", artist: "Buddy Holly" },
    { title: "Greatest Hits", artist: "The Mamas & The Papas" },
    { title: "King Of The Delta Blues Singers Vol. 2", artist: "Robert Johnson" },
    { title: "Changesone", artist: "David Bowie" },
    { title: "The Battle Of Los Angeles", artist: "Rage Against The Machine" },
    { title: "Presenting The Fabulous Ronettes Featuring Veronica", artist: "The Ronettes" },
    { title: "Kid A", artist: "Radiohead" },
    { title: "Grievous Angel", artist: "Gram Parsons" },
    { title: "At Budokan", artist: "Cheap Trick" },
    { title: "Anthology", artist: "The Supremes" },
    { title: "Sleepless", artist: "Peter Wolf" },
    { title: "Another Green World", artist: "Brian Eno" },
    { title: "Outlandos DAmour", artist: "The Police" },
    { title: "To Bring You My Love", artist: "PJ Harvey" },
    { title: "Here Come The Warm Jets", artist: "Brian Eno" },
    { title: "All Things Must Pass", artist: "George Harrison" },
    { title: "Number 1 Record", artist: "Big Star" },
    { title: "In Utero", artist: "Nirvana" },
    { title: "Sea Change", artist: "Beck" },
    { title: "Tragic Kingdom", artist: "No Doubt" },
    { title: "Boys Dont Cry", artist: "The Cure" },
    { title: "Live At The Harlem Square Club 1963", artist: "Sam Cooke" },
    { title: "Criminal Minded", artist: "Boogie Down Productions" },
    { title: "Rum Sodomy And The Lash", artist: "The Pogues" },
    { title: "Suicide", artist: "Suicide" },
    { title: "Q: Are We Not Men? A: We Are Devo!", artist: "Devo" },
    { title: "In Color", artist: "Cheap Trick" },
    { title: "The World Is A Ghetto", artist: "War" },
    { title: "Fly Like An Eagle", artist: "Steve Miller Band" },
    { title: "Back In The USA", artist: "MC5" },
    { title: "Music", artist: "Madonna" },
    { title: "Ritual De Lo Habitual", artist: "Janes Addiction" },
    { title: "Getz/Gilberto", artist: "Stan Getz And Joao Gilberto Featuring Antonio Carlos Jobim" },
    { title: "Synchronicity", artist: "The Police" },
    { title: "Third/Sister Lovers", artist: "Big Star" },
    { title: "For Everyman", artist: "Jackson Browne" },
    { title: "John Prine", artist: "John Prine" },
    { title: "Strictly Business", artist: "EPMD" },
    { title: "Love It To Death", artist: "Alice Cooper" },
    { title: "How Will The Wolf Survive?", artist: "Los Lobos" },
    { title: "Here My Dear", artist: "Marvin Gaye" },
    { title: "Tumbleweed Connection", artist: "Elton John" },
    { title: "The Blueprint", artist: "Jay-Z" },
    { title: "Golden Hits", artist: "The Drifters" },
    { title: "Live Through This", artist: "Hole" },
    { title: "Love And Theft", artist: "Bob Dylan" },
    { title: "Elton John", artist: "Elton John" },
    { title: "Metal Box", artist: "Public Image Ltd." },
    { title: "Document", artist: "R.E.M." },
    { title: "Heaven Up Here", artist: "Echo & The Bunnymen" },
    { title: "Hysteria", artist: "Def Leppard" },
    { title: "A Rush Of Blood To The Head", artist: "Coldplay" },
    { title: "Live In Europe", artist: "Otis Redding" },
    { title: "Tunnel Of Love", artist: "Bruce Springsteen" },
    { title: "The Paul Butterfield Blues Band", artist: "The Paul Butterfield Blues Band" },
    { title: "The Score", artist: "Fugees" },
    { title: "Radio", artist: "LL Cool J" },
    { title: "I Want To See The Bright Lights Tonight", artist: "Richard & Linda Thompson" },
    { title: "Faith", artist: "George Michael" },
    { title: "The Smiths", artist: "The Smiths" },
    { title: "Armed Forces", artist: "Elvis Costello And The Attractions" },
    { title: "Life After Death", artist: "The Notorious B.I.G." },
    { title: "Branded Man", artist: "Merle Haggard" },
    { title: "All Time Greatest Hits", artist: "Loretta Lynn" },
    { title: "Maggot Brain", artist: "Funkadelic" },
    { title: "Mellon Collie And The Infinite Sadness", artist: "Smashing Pumpkins" },
    { title: "Voodoo", artist: "DAngelo" },
    { title: "Guitar Town", artist: "Steve Earle" },
    { title: "Entertainment!", artist: "Gang Of Four" },
    { title: "All The Young Dudes", artist: "Mott The Hoople" },
    { title: "Vitalogy", artist: "Pearl Jam" },
    { title: "That's The Way Of The World", artist: "Earth Wind & Fire" },
    { title: "Shes So Unusual", artist: "Cyndi Lauper" },
    { title: "New Day Rising", artist: "Hüsker Dü" },
    { title: "Destroyer", artist: "Kiss" },
    { title: "Yo! Bum Rush The Show", artist: "Public Enemy" },
    { title: "Tres Hombres", artist: "ZZ Top" },
    { title: "Born Under A Bad Sign", artist: "Albert King" },
    { title: "Touch", artist: "Eurythmics" }
  ],

  random: function() {
    return Albums.albums[Math.floor(Math.random() * (Albums.albums.length + 1))];
  }
};
